package de.bitbrain.shelter.animation;

public enum AnimationTypes {
   PLAYER_STANDING_SOUTH,
   PLAYER_STANDING_SOUTH_WEST,
   PLAYER_STANDING_WEST,
   PLAYER_STANDING_NORTH_WEST,
   PLAYER_STANDING_NORTH,
   PLAYER_STANDING_NORTH_EAST,
   PLAYER_STANDING_EAST,
   PLAYER_STANDING_SOUTH_EAST;
}
